version: 2

sources:
  - name: mailchimp
    database: airbyte
    tables:
      - name: automations
      - name: campaigns
      - name: lists
      - name: email_activity
      - name: reports
      - name: unsubscribes